### PR TITLE
Attempt to fix travis deploy

### PR DESCRIPTION
**Pull request by manucorporat**

### CODE REVIEW

**Comment by abeaumont** [comment]
@manucorporat It doesn't seem to work, look at travis logs for details.

**Comment by manucorporat** [comment]
Where?

**Comment by manucorporat** [comment]
I have taken this as a example: https://github.com/linux-rdma/rdma-core/pull/93/files

**Comment by abeaumont** [comment]
```
$ git archive --output libuast.tar.gz `git stash create`
fatal: Not a git repository (or any of the parent directories): .git
usage: git archive [<options>] <tree-ish> [<path>...]
   or: git archive --list
   or: git archive --remote <repo> [--exec <cmd>] [<options>] <tree-ish> [<path>...]
   or: git archive --remote <repo> [--exec <cmd>] --list
```

**Pull request merged**
