### PR TITLE
Finish porting to Windows

### PR DESCRIPTION
**Pull request by vmarkovtsev**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@juanjux I add appveyor config which generate two build artifacts - mingw and msvc++ archived prefixes.

You need to manually enable AppVeyor for bblfsh/libuast here: https://ci.appveyor.com/projects/new

**Comment by juanjux** [comment]
Excellent work dealing with the Beast. I just added the project to appveyor.

**Comment by vmarkovtsev** [comment]
"Project not found or access denied." at https://ci.appveyor.com/project/bblfsh/libuast I guess we need to enable public readonly access (not sure)

**Comment by juanjux** [comment]
Done. I've given `view` and `run build` permissions for users. I'm waiting for travis to finish to merge this, but it seems it doesn't work very well today.

**Comment by juanjux** [comment]
Mmmm, still now showing, let me check it.

**Comment by juanjux** [comment]
Found the problem, since I logged with my github user it's at:

https://ci.appveyor.com/project/juanjux/libuast

Do we have a bblfsh user for appveyor or do I register a new one?

**Comment by vmarkovtsev** [comment]
AppVeyor offers you to enable projects in all the organizations you are allowed to. For example, I can enable it for our projects in src-d. I guess we need to ask Máximo to grant you the permissions.

**Comment by juanjux** [comment]
Yes, I see `src-d` projects but not bblfsh, @mcuadros could you fix the permissions?

**Comment by mcuadros** [comment]
Done, you need to push something

**Comment by vmarkovtsev** [comment]
I will push the badge

**Pull request merged**
