### PR TITLE
Add AppVeyor tag deployment

### PR DESCRIPTION
**Pull request by vmarkovtsev**
We need to add an encrypted key:

image

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@mcuadros Could you please take a look

**Comment by vmarkovtsev** [comment]
@juanjux Since this is approved and merged, would you kindly make the first release with windows support?

**Comment by juanjux** [comment]
@vmarkovtsev done.

**Comment by vmarkovtsev** [comment]
Thanks! According to https://ci.appveyor.com/project/mcuadros/libuast/build/job/iba6m4q9x3aj4b3q we are unauthorized.

@mcuadros Could you please add the token as I described in the issue description?

**Pull request merged**
